//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S2.L2C {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S2.L2C.Strings1", typeof(Strings1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   BEEP!   .
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strängen {0} kan inte tolkas som en godkänd angivelse av timme..
        /// </summary>
        internal static string ErrorHour {
            get {
                return ResourceManager.GetString("ErrorHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Värdet {0} kan inte tolkas som en godkänd angivelse av maximalt intervall..
        /// </summary>
        internal static string ErrorMaxNumber {
            get {
                return ResourceManager.GetString("ErrorMaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strängen {0} kan inte tolkas som en godkänd angivelse av minut..
        /// </summary>
        internal static string ErrorMinute {
            get {
                return ResourceManager.GetString("ErrorMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strängen {0} kan inte tolkas som en tid på formatet HH:mm.
        /// </summary>
        internal static string ErrorTime {
            get {
                return ResourceManager.GetString("ErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========================================.
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ||       Modellnr.: 1DV402S2L2C       ||.
        /// </summary>
        internal static string Modellnr {
            get {
                return ResourceManager.GetString("Modellnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test av standardkonstruktor..
        /// </summary>
        internal static string Test1 {
            get {
                return ResourceManager.GetString("Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar konstruktorer så att undantag kastas då timme {0} och minut {1} tilldelas negativa värden..
        /// </summary>
        internal static string Test10 {
            get {
                return ResourceManager.GetString("Test10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar konstruktorer så att undantag kastas då tid {0} och alarmtid {1} tilldelas ickenumeriska värden..
        /// </summary>
        internal static string Test11 {
            get {
                return ResourceManager.GetString("Test11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar att konstruktorn NumberDisplay inte accepterar en parameter {0} som har ett negativt värde..
        /// </summary>
        internal static string Test12 {
            get {
                return ResourceManager.GetString("Test12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar att konstruktorn ClockDisplay inte accepterar en parameter {0} som har ett felaktigt värde..
        /// </summary>
        internal static string Test13 {
            get {
                return ResourceManager.GetString("Test13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar att konstruktorn AlarmDisplay inte accepterar en parameter {0} som har ett felaktigt värde..
        /// </summary>
        internal static string Test14 {
            get {
                return ResourceManager.GetString("Test14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar att konstruktorn AlarmDisplay inte accepterar för litet antal parametrar..
        /// </summary>
        internal static string Test15 {
            get {
                return ResourceManager.GetString("Test15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test av konstruktorn med två parametrar ({0},  {1})..
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test av konstruktorn med fyra parametrar..
        /// </summary>
        internal static string Test3 {
            get {
                return ResourceManager.GetString("Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test av konstruktorn med variabelt antal, dock minst två, parametrar av typen string..
        /// </summary>
        internal static string Test4 {
            get {
                return ResourceManager.GetString("Test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ställer befintligt AlarmClock objekt till {0} och låter den gå i 13 minuter..
        /// </summary>
        internal static string Test5 {
            get {
                return ResourceManager.GetString("Test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ställer befintligt AlarmClock objekt till tiden {0} och alarmtiden till {1} låter den gå i 6 minuter..
        /// </summary>
        internal static string Test6 {
            get {
                return ResourceManager.GetString("Test6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar egenskaperna så att undantag kastas då tid {0} och alarmtid {1} tilldelas felaktiga värden..
        /// </summary>
        internal static string Test7 {
            get {
                return ResourceManager.GetString("Test7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar konstruktorer så att undantag kastas då tid {0} och alarmtid {1} tilldelas felaktiga värden..
        /// </summary>
        internal static string Test8 {
            get {
                return ResourceManager.GetString("Test8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar konstruktorer så att undantag kastas då tid {0} och alarmtid {1} tilldelas negativa värden..
        /// </summary>
        internal static string Test9 {
            get {
                return ResourceManager.GetString("Test9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla tester körda.
        /// </summary>
        internal static string TestOK {
            get {
                return ResourceManager.GetString("TestOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ||      Väckarklockan URLED (TM)      ||.
        /// </summary>
        internal static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
    }
}
